#!/usr/bin/env bash
# Merge OpenCode provider config fragments into the combined provider
# config — shipped by the opencode-config mixin
# (mixins/opencode-config/files/home/.sandbox-kit/merge-opencode-config.sh)
# and run by that mixin's provider-config hook (sourced by the entrypoint
# runtime before opencode starts). Do not edit the hook's call site for
# provider-specific behavior: changes belong here.
#
# How the pieces fit together:
#   - Every provider mixin (mixins/zeldoc, mixins/copilot, ...) ships a
#     pure-JSON fragment to ~/.config/opencode/providers.d/NN-<name>.json.
#   - This script merges them, in filename order, into ONE config file
#     (default ~/.config/opencode/providers.jsonc). The opencode-config
#     mixin sets OPENCODE_CONFIG to that path, so opencode loads the
#     merged result between the global and project config layers. The
#     file is rebuilt from the fragments at every sandbox start —
#     hand-edits are lost.
#   - enabled_providers / disabled_providers are UNIONED across fragments
#     (everything else: objects merge recursively, later fragments win
#     scalar conflicts — e.g. `model`). That is what lets provider mixins
#     compose: zeldoc + copilot both stay enabled, and the default model
#     is whichever fragment sorts last (zeldoc's 20- beats copilot's 10-).
#   - Fragments must be comment-free JSON (jq does the merging); a
#     .jsonc fragment in the directory is a hard error.
#
# Exit codes: 0 = merged (or nothing to merge); 1 = fragment error —
# the previous output file is left untouched in that case.
set -euo pipefail

FRAG_DIR="${OPENCODE_PROVIDERS_DIR:-$HOME/.config/opencode/providers.d}"
OUT="${1:-$HOME/.config/opencode/providers.jsonc}"

mkdir -p "$(dirname "$OUT")"

seed() {
    # Nothing to merge: write the minimal valid config so OPENCODE_CONFIG
    # always points at a loadable file.
    printf '{\n  "$schema": "https://opencode.ai/config.json"\n}\n'
}

fail() {
    echo "ERROR [provider-config]: $*" >&2
    exit 1
}

if [ ! -d "$FRAG_DIR" ]; then
    seed > "$OUT"
    echo "[provider-config] no provider fragments ($FRAG_DIR missing) — wrote the empty combined config"
    exit 0
fi

shopt -s nullglob
fragments=("$FRAG_DIR"/*.json)
jsonc=("$FRAG_DIR"/*.jsonc)
shopt -u nullglob

if [ "${#jsonc[@]}" -gt 0 ]; then
    fail "comment-bearing fragments are not supported: ${jsonc[*]} — provider fragments in $FRAG_DIR must be comment-free .json (jq does the merging)"
fi

if [ "${#fragments[@]}" -eq 0 ]; then
    seed > "$OUT"
    echo "[provider-config] no provider fragments in $FRAG_DIR — wrote the empty combined config"
    exit 0
fi

tmp="$(mktemp "$(dirname "$OUT")/.providers.jsonc.XXXXXX")"
tmp_wrapped="${tmp}.wrapped"
trap 'rm -f "$tmp" "$tmp_wrapped"' EXIT

if command -v jq > /dev/null 2>&1; then
    for f in "${fragments[@]}"; do
        if ! jq -e 'type == "object"' "$f" > /dev/null 2>&1; then
            fail "$f is not a valid JSON object — fix or remove it (the previous combined config was left in place)"
        fi
    done
    # Object values merge recursively; later fragments win scalar
    # conflicts (jq's `*`), while the provider allow/deny lists union.
    jq -s '
      reduce .[] as $f (
        {};
        (. * $f)
        + (if ($f | has("enabled_providers")) then
            {enabled_providers: (((.enabled_providers // []) + $f.enabled_providers) | unique)}
          else {} end)
        + (if ($f | has("disabled_providers")) then
            {disabled_providers: (((.disabled_providers // []) + $f.disabled_providers) | unique)}
          else {} end)
      )
    ' "${fragments[@]}" > "$tmp"
elif [ "${#fragments[@]}" -eq 1 ]; then
    # jq-less fallback: a single fragment needs no merging.
    cp -- "${fragments[0]}" "$tmp"
else
    fail "jq is not available and there are ${#fragments[@]} fragments to merge — install jq (the template images ship it)"
fi

{
    printf '// GENERATED by ~/.sandbox-kit/merge-opencode-config.sh — do not edit.\n'
    printf '// Fragments: %s\n' "$(basename -a "${fragments[@]}" | paste -sd' ' -)"
    printf '// Edit the owning mixin in docker-sandboxing (or a providers.d/ fragment) and restart the sandbox.\n'
    cat "$tmp"
} > "${tmp}.wrapped"
mv -f "${tmp}.wrapped" "$OUT"

echo "[provider-config] merged ${#fragments[@]} provider fragment(s) ($(basename -a "${fragments[@]}" | paste -sd' ' -)) -> $OUT"
