#!/bin/bash
# Merge OpenCode provider config fragments.
#
# Fragments land in ~/.config/opencode/mixins.d/ as *.json (shipped by
# provider mixins' images). This merge unions the enabled_*/disabled_*
# lists so mixins compose (zeldoc + copilot both stay enabled) and merges
# the rest recursively (later fragments win scalar conflicts). The result
# is the combined config OPENCODE_CONFIG points at.
#
# Runs from the workload entrypoint shim and also as a lifecycle startup
# hook — both paths are idempotent.
set -euo pipefail

FRAG_DIR="${OPENCODE_MIXINS_DIR:-$HOME/.config/opencode/mixins.d}"
OUT="${OPENCODE_CONFIG:-$HOME/.config/opencode/sandbox-mixins.jsonc}"

mkdir -p "$(dirname "$OUT")"

seed() {
    # Nothing to merge: write the minimal valid config so OPENCODE_CONFIG
    # always points at a loadable file.
    printf '{\n  "$schema": "https://opencode.ai/config.json"\n}\n'
}

fail() {
    echo "ERROR [mixins-config]: $*" >&2
    exit 1
}

if [ ! -d "$FRAG_DIR" ]; then
    seed > "$OUT"
    echo "[mixins-config] no mixins fragments ($FRAG_DIR missing) — wrote the empty combined config"
    exit 0
fi

shopt -s nullglob
fragments=("$FRAG_DIR"/*.json)
jsonc=("$FRAG_DIR"/*.jsonc)
shopt -u nullglob

if [ "${#jsonc[@]}" -gt 0 ]; then
    fail "comment-bearing fragments are not supported: ${jsonc[*]} — mixins fragments in $FRAG_DIR must be comment-free .json (jq does the merging)"
fi

if [ "${#fragments[@]}" -eq 0 ]; then
    seed > "$OUT"
    echo "[mixins-config] no mixins fragments in $FRAG_DIR — wrote the empty combined config"
    exit 0
fi

tmp="$(mktemp "$(dirname "$OUT")/.sandbox-mixins.jsonc.XXXXXX")"
tmp_wrapped="${tmp}.wrapped"
trap 'rm -f "$tmp" "$tmp_wrapped"' EXIT

if command -v jq > /dev/null 2>&1; then
    for f in "${fragments[@]}"; do
        if ! jq -e 'type == "object"' "$f" > /dev/null 2>&1; then
            fail "$f is not a valid JSON object — fix or remove it (the previous combined config was left in place)"
        fi
    done
    # Object values merge recursively; later fragments win scalar
    # conflicts (jq's `*`). Array-valued keys whose name starts
    # with "enabled_" or "disabled_" (e.g. enabled_providers) are unioned
    # instead — that is what lets mixins compose (zeldoc + copilot both
    # stay enabled).
    jq -s '
    def unionkey:
        [keys[] | select(test("^enabled_|^disabled_"))] | .[];
    reduce .[] as $f (
        {};
        . as $acc
        | (. * $f)
        + (reduce ($f | unionkey) as $k ({};
            .[$k] = ((($acc[$k] // []) + ($f[$k] // [])) | unique)))
    )
    ' "${fragments[@]}" > "$tmp"
elif [ "${#fragments[@]}" -eq 1 ]; then
    # jq-less fallback: a single fragment needs no merging.
    cp -- "${fragments[0]}" "$tmp"
else
    fail "jq is not available and there are ${#fragments[@]} fragments to merge — install jq (the workload images ship it)"
fi

{
    printf '// GENERATED by the global-opencode-config mixin startup command — do not edit.\n'
    printf '// Fragments: %s\n' "$(basename -a "${fragments[@]}" | paste -sd' ' -)"
    printf '// Edit the owning mixin in docker-sandboxing (or a mixins.d/ fragment) and restart the sandbox.\n'
    cat "$tmp"
} > "${tmp}.wrapped"
mv -f "${tmp}.wrapped" "$OUT"

echo "[mixins-config] merged ${#fragments[@]} mixins fragment(s) ($(basename -a "${fragments[@]}" | paste -sd' ' -)) -> $OUT"
